Repository DreamWeave-MP/Dreamweave, pull requests merged in 2023-10, with the labels that each got.

#69 FIX(Client): Allow Colors to be input from chat window
  apps/openmw/mwmp/GUI/GUIChat.cpp
Labels: bug, enhancement

#78 Feat(CI): Run actions on fix/ and feat/ branches
  .github/workflows/openmw-mp.yml
Labels: enhancement

#75 Fix(CI): Update ubuntu and build as RelWithDeb again
  .github/workflows/openmw-mp.yml
Labels: enhancement

#50 Feature(CI): Add Windows Builds
  .github/workflows/openmw-mp.yml
  .github/workflows/windows.yml
  CI/before_script.msvc.sh
  CI/build_raknet.sh
  CI/make_package.msvc.sh
  CI/make_package.ubuntu.sh
  CMakeLists.txt
  cmake/FindRakNet.cmake
Labels: enhancement

#87 Fix(server): send correct version to masterserver
  apps/openmw-mp/MasterClient.cpp
Labels: bug

#80 Cleanup(server): Refactor code for Lua function dispatch
  apps/openmw-mp/Script/LangLua/LangLua.cpp
  apps/openmw-mp/Script/LangLua/LangLua.hpp
Labels: documentation, enhancement
